import React from 'react';
import { MantraParts } from '../types';
import { Check, Share2, RotateCcw, ArrowLeft } from 'lucide-react';

interface ShareViewProps {
  mantra: MantraParts;
  daysStreak: number;
  onContinue: () => void;
  onResetGoal: () => void;
}

export const ShareView: React.FC<ShareViewProps> = ({ mantra, daysStreak, onContinue, onResetGoal }) => {
  return (
    <div className="flex flex-col items-center w-full max-w-md mx-auto animate-fade-in-up">
      
      {/* Celebration Header */}
      <div className="text-center mb-6">
        <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-green-100 text-green-600 mb-4 shadow-sm border-4 border-white">
          <Check size={40} strokeWidth={3} />
        </div>
        <h2 className="text-3xl font-bold text-gray-800 font-serif">打卡成功!</h2>
        <p className="text-gray-500 mt-2">你离更好的自己又近了一步</p>
      </div>

      {/* Share Card (Visual representation of what would be shared) */}
      <div className="w-full bg-gradient-to-br from-primary-600 to-primary-800 text-white p-8 rounded-2xl shadow-2xl relative overflow-hidden mb-8">
        <div className="absolute top-0 right-0 -mr-8 -mt-8 w-32 h-32 bg-white opacity-10 rounded-full blur-2xl"></div>
        <div className="absolute bottom-0 left-0 -ml-8 -mb-8 w-32 h-32 bg-white opacity-10 rounded-full blur-2xl"></div>
        
        <div className="relative z-10 text-center space-y-4">
          <p className="text-primary-100 text-sm font-medium tracking-widest uppercase">My Habit Journey</p>
          
          <div className="py-4 border-t border-white/20 border-b">
            <p className="text-2xl font-serif font-bold leading-relaxed">
              "{mantra.identity}"
            </p>
          </div>

          <div className="flex justify-center items-end gap-2 pt-2">
            <span className="text-5xl font-bold">{daysStreak}</span>
            <span className="text-lg text-primary-200 pb-1 font-medium">天连续坚持</span>
          </div>
          
          <p className="text-xs text-primary-200 mt-4 opacity-80">Generated by HabitMantra</p>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-col gap-3 w-full">
        <button 
          onClick={() => alert("请截屏上方卡片分享至朋友圈")}
          className="w-full py-4 bg-gray-900 text-white rounded-xl font-semibold shadow-lg hover:bg-gray-800 transition-colors flex items-center justify-center gap-2"
        >
          <Share2 size={20} />
          分享至朋友圈
        </button>
        
        <div className="grid grid-cols-2 gap-3 mt-2">
          <button 
            onClick={onContinue}
            className="w-full py-3 bg-white border border-gray-200 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-xl font-medium text-sm flex items-center justify-center gap-2 transition-colors"
          >
            <ArrowLeft size={16} />
            查看今日咒语
          </button>

          <button 
            onClick={onResetGoal}
            className="w-full py-3 bg-white border border-gray-200 text-gray-600 hover:text-red-600 hover:bg-red-50 hover:border-red-100 rounded-xl font-medium text-sm flex items-center justify-center gap-2 transition-colors"
          >
            <RotateCcw size={16} />
            开启新习惯
          </button>
        </div>
      </div>

    </div>
  );
};